# Generated by Django 5.1.7 on 2025-04-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_reservation_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
